console.time('Your code took')
console.log('Hello console')
console.log(5+50)
console.log(true)
console.log([5,6,8,0,10])
console.log({student:'Niket', marks:98})
console.table({student:'Niket', marks:98})
console.warn("danger")
//console.clear()
console.timeEnd('Your code took')
console.error('this is an error')